apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
  namespace: guestbook-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook-container
        image: reyredd/guestbook:3c37e5f
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: guestbook-app-config
              key: DATABASE_URL
